version: "3"

volumes:
  mongo_data: {}
  mongo_backup: {}
  node_logs: {}
  backend_node_module: {}

networks:
  app-network:
    driver: bridge

services:
  backend:
    restart: always
    container_name: <%=project_slug%>_node_test
    build:
      context: .
      dockerfile: compose/node/Dockerfile_dev
    env_file:
      - .env
    volumes:
      - ./backend:/home/app/<%=project_slug%>
      - backend_node_module:/home/app/<%=project_slug%>/node_modules
      - node_logs:/home/app/<%=project_slug%>/logs
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    networks:
      - app-network
    # tty: true
  mongo:
    restart: always
    container_name: <%=project_slug%>_mongo_test
    image: mongo:4.2
    command: mongod --storageEngine wiredTiger
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
      - mongo_backup:/data/backup
#    ports:
#      - '27017:27017'
    networks:
      - app-network

  redis:
    image: redis:6.2.13-alpine
    container_name: <%=project_slug%>_redis_local
    networks:
      - app-network

