version: "3"

volumes:
  mongo_data: {}
  mongo_backup: {}
  node_logs: {}
  media_data: {}
  backend_node_module: {}

networks:
  app-network:
    driver: bridge

services:
  backend:
    restart: always
    image: registry.astraler.com/<%=project_slug%>:latest
    container_name: <%=project_slug%>_node_production
    # build:
    #   context: .
    #   dockerfile: compose/node/Dockerfile.production
    env_file:
      - .env
    volumes:
      - backend_node_module:/home/app/<%=project_slug%>/node_modules
      - node_logs:/home/app/<%=project_slug%>/logs
      - media_data:/home/app/<%=project_slug%>/uploads
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

    # tty: true
  mongo:
    restart: always
    image: mongo:4.2
    container_name: <%=project_slug%>_mongo_production
    env_file:
      - .env
    command: mongod --storageEngine wiredTiger
    volumes:
      - mongo_data:/data/db
      - mongo_backup:/data/backup
    networks:
      - app-network

  redis:
    image: redis:6.2.13-alpine
    container_name: <%=project_slug%>_redis_production
    networks:
      - app-network

  nginx:
    restart: always
    build: ./compose/nginx
    container_name: <%=project_slug%>_nginx_production
    depends_on:
      -  backend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

